"""Battery Guardian: LaunchAgent automation and share-report generation."""

import json
import logging
import os
import subprocess
import sys
from datetime import datetime

from bg_config import VERSION
from bg_state import state, state_lock

logger = logging.getLogger("battery_guardian")

# Path to the true entry point, regardless of which module __file__ is in.
_ENTRY_POINT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "battery_guardian_web.py")


def generate_share_report():
    """Generate a plain-text scan report for clipboard sharing."""
    m = state["metrics"]
    lines = [
        f"Battery Guardian v{VERSION} Scan Report",
        f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"Model: {state.get('mac_model', 'Mac')}",
        f"Serial: {m.get('serial', '--')}",
        "",
        f"Verdict: {state['verdict']}",
        f"Health Score: {state['health_score']}/100",
        f"Cycles: {m.get('cycle_count', '--')}",
        f"Health: {m.get('health', '--')}",
        f"Operating Time: {m.get('op_time', '--')}",
        "",
        "Checks:",
    ]
    for item in state.get("log", []):
        icon = "✅" if item["status"] == "success" else "⚠️" if item["status"] == "warning" else "ℹ️" if item["status"] == "info" else "❌"
        lines.append(f"  {icon} {item['title']}")
    lines.append("")
    lines.append("Generated by Battery Guardian | github.com/Dannyjay-hub/Battery-Guardian-for-Mac")
    return "\n".join(lines)


def install_launch_agent(days, hour=20, minute=0):
    """Install a macOS LaunchAgent for scheduled headless scans."""
    try:
        safe_dir = os.path.expanduser("~/.battery_guardian")
        if not os.path.exists(safe_dir):
            os.makedirs(safe_dir)

        if getattr(sys, 'frozen', False):
            # Running as a compiled .app bundle — Python files don't exist as loose files.
            # The LaunchAgent calls the binary directly with --auto flag.
            safe_script = None
        else:
            # Running from source — copy the entry-point script to a stable location.
            safe_script = os.path.join(safe_dir, "bg_auto.py")
            with open(_ENTRY_POINT, "r") as src, open(safe_script, "w") as dst:
                dst.write(src.read())

        python_path = sys.executable

        if safe_script:
            # Source mode: python + script + --auto
            program_args_xml = (
                f"        <string>{python_path}</string>\n"
                f"        <string>{safe_script}</string>\n"
                f"        <string>--auto</string>"
            )
        else:
            # Frozen mode: binary + --auto
            program_args_xml = (
                f"        <string>{python_path}</string>\n"
                f"        <string>--auto</string>"
            )

        plist_path = os.path.expanduser("~/Library/LaunchAgents/com.batteryguardian.daily.plist")
        plist_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.batteryguardian.daily</string>
    <key>ProgramArguments</key>
    <array>
{program_args_xml}
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>{hour}</integer>
        <key>Minute</key>
        <integer>{minute}</integer>
    </dict>
    <key>RunAtLoad</key>
    <false/>
    <key>StandardOutPath</key>
    <string>/tmp/battery_guardian.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/battery_guardian.err</string>
</dict>
</plist>"""
        with open(plist_path, "w") as f:
            f.write(plist_content)

        subprocess.run(["launchctl", "unload", plist_path], capture_output=True, check=False)
        subprocess.run(["launchctl", "load", plist_path], capture_output=True, check=True)

        config_path = os.path.join(safe_dir, "automation_config.json")
        config = {
            "installed_at": datetime.now().isoformat(),
            "expires_after_days": days,
            "hour": hour,
            "minute": minute,
        }
        with open(config_path, "w") as f:
            json.dump(config, f)

        return True, f"Scheduled ({hour}:{minute:02d}) for {days} days."
    except Exception as e:
        logger.error(f"LaunchAgent error: {e}")
        return False, str(e)
